version: '3.5'

services:
  db:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5454:80'
    depends_on:
      - db